-- MySQL Script generated by MySQL Workbench
-- Tue Mar 25 19:54:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gvrer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gvrer` ;

-- -----------------------------------------------------
-- Schema gvrer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gvrer` DEFAULT CHARACTER SET utf8 ;
USE `gvrer` ;

-- -----------------------------------------------------
-- Table `gvrer`.`motivodaviagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gvrer`.`motivodaviagem` (
  `MOTIVODAVIAGEMID` INT NOT NULL AUTO_INCREMENT,
  `NOMEMOTIVODAVIAGEM` VARCHAR(200) NULL,
  PRIMARY KEY (`MOTIVODAVIAGEMID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gvrer`.`itinerario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gvrer`.`itinerario` (
  `itinerarioid` INT NOT NULL AUTO_INCREMENT,
  `nomeitinerario` VARCHAR(200) NULL,
  `valor` FLOAT NULL,
  `observacoes` VARCHAR(200) NULL,
  `seguroviagem` VARCHAR(45) NULL,
  `dataida` TIMESTAMP NULL,
  `horaida` TIME NULL,
  `datavolta` TIMESTAMP NULL,
  `horavolta` TIME NULL,
  `motivodaviagem_MOTIVODAVIAGEMID` INT NOT NULL,
  PRIMARY KEY (`itinerarioid`),
  INDEX `fk_itinerario_motivodaviagem_idx` (`motivodaviagem_MOTIVODAVIAGEMID` ASC) VISIBLE,
  CONSTRAINT `fk_itinerario_motivodaviagem`
    FOREIGN KEY (`motivodaviagem_MOTIVODAVIAGEMID`)
    REFERENCES `gvrer`.`motivodaviagem` (`MOTIVODAVIAGEMID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gvrer`.`destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gvrer`.`destino` (
  `destinoid` INT NOT NULL AUTO_INCREMENT,
  `nomedestino` VARCHAR(200) NULL,
  `observacaodestino` VARCHAR(200) NULL,
  PRIMARY KEY (`destinoid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gvrer`.`itinerario_destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gvrer`.`itinerario_destino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sequencia` TINYINT NULL,
  `itinerario_itinerarioid` INT NOT NULL,
  `destino_destinoid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itinerario_destino_itinerario1_idx` (`itinerario_itinerarioid` ASC) VISIBLE,
  INDEX `fk_itinerario_destino_destino1_idx` (`destino_destinoid` ASC) VISIBLE,
  CONSTRAINT `fk_itinerario_destino_itinerario1`
    FOREIGN KEY (`itinerario_itinerarioid`)
    REFERENCES `gvrer`.`itinerario` (`itinerarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itinerario_destino_destino1`
    FOREIGN KEY (`destino_destinoid`)
    REFERENCES `gvrer`.`destino` (`destinoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
